import { MutationCtx } from "../../../../_generated/server";
import { Id } from "../../../../_generated/dataModel";
import { Doc } from "../../../../_generated/dataModel";

export async function createServiceAndBookingFromQuote(
    ctx: MutationCtx,
    quote: Doc<"quotes">,
    clientTimezone: string,
): Promise<{
    serviceId: Id<"services">;
    bookingId: Id<"bookings">;
    orderNo: string;
}> {
    const creativeProfile = await ctx.db
        .query("creativeProfiles")
        .withIndex("by_userId", q => q.eq("userId", quote.creativeId))
        .first();

    const defaultCategoryId = creativeProfile?.skills?.[0];
    if (!defaultCategoryId) {
        throw new Error(
            "Creative must have at least one skill category before accepting quotes",
        );
    }

    const toMinutes = (t: string) => {
        const [h, m] = t.split(":").map(Number);
        return h * 60 + m;
    };
    const startMinutes = toMinutes(quote.startTime);
    const endMinutes = toMinutes(quote.endTime);
    const duration = endMinutes - startMinutes;
    const dayOfWeek = new Date(quote.proposedDate).getDay();

    const serviceId = await ctx.db.insert("services", {
        userId: quote.creativeId,
        name: quote.title,
        description: quote.details,
        categoryId: defaultCategoryId,
        paymentSystem: "FLAT",
        serviceFee: quote.budget,
        bookingFee: Math.round(quote.budget * 0.3),
        banners: [],
        tags: ["custom-quote"],
        availability: [
            {
                day: dayOfWeek,
                start: startMinutes,
                end: endMinutes,
                selected: true,
            },
        ],
        duration,
        bufferTime: 0,
        status: "DRAFT",
        deleteStatus: false,
        stats: {
            timesOrdered: 0,
            timesCompleted: 0,
            timesCancelled: 0,
            timesRescheduled: 0,
        },
        isAutoGenerated: true,
        sourceQuoteId: quote._id,
    });

    const bookings = await ctx.db.query("bookings").collect();
    const orderNo = `WND-${bookings.length + 1001}`;
    const dateBooked = new Date(quote.proposedDate).setHours(0, 0, 0, 0);

    const bookingId = await ctx.db.insert("bookings", {
        orderNo,
        clientId: quote.clientId,
        creativeId: quote.creativeId,
        serviceId,
        dateBooked,
        startTime: startMinutes,
        endTime: endMinutes,
        status: "PENDING",
        clientTimezone,
        currency: "usd",
        serviceFee: quote.budget,
        bookingFee: Math.round(quote.budget * 0.3),
        tax: 0,
        proposedTotal: quote.budget,
        platformClientFeePercent: 5,
        platformCreativeFeePercent: 15,
        platformClientFeeAmount: Math.round(quote.budget * 0.05),
        platformCreativeFeeAmount: Math.round(quote.budget * 0.15),
        upfrontChargeAmount:
            Math.round(quote.budget * 0.3) + Math.round(quote.budget * 0.05),
        remainingDueAmount: quote.budget - Math.round(quote.budget * 0.3),
        paymentPhase: "NONE",
        note: `From accepted quote: ${quote.title}`,
        jobCompletionDocs: [],
        updatedAt: Date.now(),
        rescheduleStatus: "NONE",
        rescheduleCount: 0,
        rescheduleHistory: [],
    });

    return { serviceId, bookingId, orderNo };
}
